from __future__ import annotations

ANALYSIS_JOB_STATE_DIR_ENV_VAR = "LDQ_ANALYSIS_JOB_STATE_DIR"
ANALYSIS_JOB_DIR_NAME = "analysis_jobs"
ANALYSIS_JOB_DB_FILENAME = "analysis_jobs.sqlite3"
ANALYSIS_JOB_ARTIFACTS_DIR_NAME = "artifacts"

CELERY_BROKER_URL_ENV_VAR = "CELERY_BROKER_URL"
CELERY_RESULT_BACKEND_ENV_VAR = "CELERY_RESULT_BACKEND"
CELERY_TASK_ALWAYS_EAGER_ENV_VAR = "CELERY_TASK_ALWAYS_EAGER"
DEFAULT_CELERY_BROKER_URL = "redis://localhost:6379/0"
DEFAULT_CELERY_RESULT_BACKEND = "redis://localhost:6379/1"
