from __future__ import annotations

FREE_TEXT_STRUCTURED_TAGS = {
    "address",
    "date",
    "phone",
    "numeric",
    "count",
    "quantity",
    "amount",
    "rate",
    "width",
    "identifier",
    "code",
    "boolean",
    "name",
    "geo_lat",
    "geo_lon",
    "coordinate_pair",
}
FREE_TEXT_STRUCTURED_NAME_TOKENS = (
    "주소",
    "소재지",
    "일자",
    "일시",
    "날짜",
    "년월",
    "전화",
    "연락처",
    "번호",
    "코드",
    "구분",
    "유형",
    "상태",
    "여부",
    "유무",
    "기관명",
    "시설명",
    "자원명",
    "학교명",
    "업소명",
    "서비스명",
    "프로그램명",
    "사업명",
    "명칭",
    "위도",
    "경도",
)
FREE_TEXT_LONG_SAMPLE_MIN_LENGTH = 12
FREE_TEXT_LONG_SAMPLE_MIN_COUNT = 2

REQUIRED_VALUE_UNIQUE_IDENTIFIER_NAME_TOKENS = (
    "고유번호",
    "고유아이디",
    "식별번호",
    "식별자",
    "일련번호",
    "관리번호",
    "등록번호",
    "허가번호",
    "면허번호",
    "접수번호",
    "문서번호",
    "데이터번호",
    "센터ID",
    "센터아이디",
    "차량ID",
    "차량아이디",
    "ID",
    "아이디",
)
REQUIRED_VALUE_NON_UNIQUE_NAME_TOKENS = (
    "명",
    "명칭",
    "이름",
    "기관",
    "부서",
    "담당",
    "경찰서",
    "시설",
    "업소",
    "주소",
    "소재지",
    "전화",
    "연락처",
    "종류",
    "유형",
    "구분",
    "상태",
    "여부",
    "유무",
    "일자",
    "날짜",
)
REQUIRED_VALUE_NULL_MAX_RATIO = 0.5
REQUIRED_VALUE_OPTIONAL_NAME_TOKENS = (
    "상세주소",
    "상세",
    "비고",
    "참고",
    "메모",
    "설명",
    "내용",
    "특이사항",
    "기타",
    "부가",
)
REQUIRED_VALUE_TAGS = {"identifier", "name", "date"}
REQUIRED_VALUE_NAME_HINT_TOKENS = ("명", "이름", "번호", "일자")

DETAIL_ADDRESS_PLACEHOLDER_VALUES = {
    "-",
    "--",
    "---",
    ".",
    "·",
    "없음",
    "해당없음",
    "해당없슴",
    "무",
    "미상",
    "불명",
    "N/A",
    "NA",
    "NULL",
    "NONE",
    "NAN",
}
COMPLETE_DETAIL_ADDRESS_VALUES = {
    "앞",
    "뒤",
    "정문",
    "후문",
    "입구",
    "출입구",
    "본관",
    "별관",
    "신관",
    "구관",
    "분관",
    "동관",
    "서관",
    "남관",
    "북관",
    "지상",
    "지하",
    "옥상",
    "주차장",
}
COMPLETE_DETAIL_ADDRESS_PATTERNS = (
    r"^[가-힣A-Z]\d?동$",
    r"^(?:B|지하)\d+층?$",
    r"^\d+층$",
    r"^\d+호$",
)

DATE_COLUMN_NAME_TOKENS = (
    "일자",
    "일시",
    "날짜",
    "년월",
    "연도",
    "년도",
    "등록일",
    "기준일",
    "개방일",
    "운영일",
    "시행일",
    "공개일",
    "마감일",
    "시작일",
    "종료일",
    "접수일",
    "처리일",
    "발생일",
    "생성일",
    "수정일",
    "갱신일",
)
TIME_ONLY_COLUMN_NAME_TOKENS = ("시간", "시각")

ROUTING_NON_UNIQUE_NAME_TOKENS = (
    "명",
    "명칭",
    "이름",
    "기관",
    "부서",
    "담당",
    "경찰서",
    "시설",
    "업소",
    "주소",
    "소재지",
)
ROUTING_TAG_TOKENS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("date", ("일자", "일시", "날짜", "년월", "등록일", "기준일")),
    ("address", ("주소", "소재지")),
    ("geo_lat", ("위도",)),
    ("geo_lon", ("경도",)),
    ("boolean", ("여부", "유무", "YN", "Yn", "yn", "Y/N")),
    ("enum", ("구분", "유형", "종류", "상태", "분류")),
    ("code", ("코드",)),
    ("name", ("명", "명칭", "이름", "기관명", "시설명", "경찰서명")),
    ("quantity", ("대수", "개수", "건수", "수량", "좌석수", "정원수")),
    ("width", ("폭", "너비")),
    ("phone", ("전화", "연락처", "휴대전화")),
)
ROUTING_NON_UNIQUE_NAME_EXCLUDED_RULES = {"duplicate_data", "number_domain"}
