from __future__ import annotations

from backend.domain.services.settings import (
    DEFAULT_COLUMN_ROUTING_CONFIDENCE,
    NORMALIZATION_SYNONYM_PATCHES,
)

SURFACE_NORMALIZATION_MIN_CANONICAL_LENGTH = 2
SURFACE_NORMALIZATION_TARGET_MIN_COUNT = 3
SURFACE_NORMALIZATION_TARGET_TO_SOURCE_COUNT_RATIO = 3
COMPACT_VARIANT_DOMINANT_VALUE_LIMIT = 5
COMPACT_VARIANT_DOMINANT_MIN_RATIO = 0.2
COMPACT_VARIANT_MIN_KEY_LEN = 2
COMPACT_VARIANT_MAX_KEY_LEN = 10
COMPACT_VARIANT_SOURCE_MAX_RATIO = 0.2

__all__ = [
    "COMPACT_VARIANT_DOMINANT_MIN_RATIO",
    "COMPACT_VARIANT_DOMINANT_VALUE_LIMIT",
    "COMPACT_VARIANT_MAX_KEY_LEN",
    "COMPACT_VARIANT_MIN_KEY_LEN",
    "COMPACT_VARIANT_SOURCE_MAX_RATIO",
    "DEFAULT_COLUMN_ROUTING_CONFIDENCE",
    "NORMALIZATION_SYNONYM_PATCHES",
    "SURFACE_NORMALIZATION_MIN_CANONICAL_LENGTH",
    "SURFACE_NORMALIZATION_TARGET_MIN_COUNT",
    "SURFACE_NORMALIZATION_TARGET_TO_SOURCE_COUNT_RATIO",
]
