from __future__ import annotations

PROFILE_SAMPLE_ROW_LIMIT = 1000
PROFILE_SAMPLE_VALUES_LIMIT = 5
PROFILE_DISTINCT_TRACK_LIMIT = 200
PROFILE_TOP_VALUE_LIMIT = 30
PROFILE_TYPE_INFERENCE_THRESHOLD = 0.8
PROFILE_UPLOADED_ROW_BUFFER_SIZE = 51
