from __future__ import annotations

VALIDATION_OUTPUT_BASE_DIR_NAME = "ldq-gpt"
VALIDATION_OUTPUT_DIR_ENV_VAR = "LDQ_VALIDATION_OUTPUT_DIR"
VALIDATION_OUTPUT_DIR_NAME = "validation"
QUALITY_DETECTION_RESULTS_CSV_NAME = "quality_detection_results.csv"
RESULTS_DIR_NAME = "results"
REPORTS_DIR_NAME = "reports"
REPORT_EXTENSION = ".xlsx"
BATCH_REPORT_FILENAME = "전체_오류_리포트.xlsx"
BATCH_COLUMN_ERROR_REPORT_FILENAME = "전체_컬럼별_데이터_오류.xlsx"
BATCH_COLUMN_ERROR_REPORT_ARCHIVE_FILENAME = "전체_컬럼별_데이터_오류.zip"
MAX_COMMENT_LENGTH = 32000
DETECTION_MATRIX_METADATA_FIELDS = [
    "dataset_name",
    "row_index",
]
