from __future__ import annotations

NUMERIC_PAIR_BASE_STEM_TOKENS = ("총", "합계", "전체", "수", "개수", "건수", "금액", "비율", "율")
TIME_ORDER_TOKENS = (
    ("시작", "종료"),
    ("개시", "종료"),
    ("접수", "처리"),
    ("등록", "수정"),
    ("생성", "수정"),
    ("발생", "종료"),
    ("출발", "도착"),
)
REFERENCE_PAIR_TOKENS = (
    ("코드", "명"),
    ("코드", "이름"),
    ("아이디", "명"),
    ("아이디", "이름"),
    ("번호", "명"),
)

FREE_TEXT_STRUCTURED_TAGS = {
    "address",
    "date",
    "phone",
    "numeric",
    "count",
    "quantity",
    "amount",
    "rate",
    "width",
    "identifier",
    "code",
    "boolean",
    "name",
    "geo_lat",
    "geo_lon",
    "coordinate_pair",
}
FREE_TEXT_STRUCTURED_NAME_TOKENS = (
    "주소",
    "소재지",
    "일자",
    "일시",
    "날짜",
    "년월",
    "전화",
    "연락처",
    "번호",
    "코드",
    "구분",
    "유형",
    "상태",
    "여부",
    "유무",
    "기관명",
    "시설명",
    "자원명",
    "학교명",
    "업소명",
    "서비스명",
    "프로그램명",
    "사업명",
    "명칭",
    "위도",
    "경도",
)
FREE_TEXT_LONG_SAMPLE_MIN_LENGTH = 12
FREE_TEXT_LONG_SAMPLE_MIN_COUNT = 2

REQUIRED_VALUE_UNIQUE_IDENTIFIER_NAME_TOKENS = (
    "고유번호",
    "고유아이디",
    "식별번호",
    "식별자",
    "일련번호",
    "관리번호",
    "등록번호",
    "허가번호",
    "면허번호",
    "접수번호",
    "문서번호",
    "데이터번호",
    "센터ID",
    "센터아이디",
    "차량ID",
    "차량아이디",
    "ID",
    "아이디",
)
REQUIRED_VALUE_NON_UNIQUE_NAME_TOKENS = (
    "명",
    "명칭",
    "이름",
    "기관",
    "부서",
    "담당",
    "경찰서",
    "시설",
    "업소",
    "주소",
    "소재지",
    "전화",
    "연락처",
    "종류",
    "유형",
    "구분",
    "상태",
    "여부",
    "유무",
    "일자",
    "날짜",
)
REQUIRED_VALUE_NULL_MAX_RATIO = 0.05
REQUIRED_VALUE_OPTIONAL_NAME_TOKENS = (
    "상세주소",
    "상세",
    "비고",
    "참고",
    "메모",
    "설명",
    "내용",
    "특이사항",
    "기타",
    "부가",
)
REQUIRED_VALUE_TAGS = {"identifier", "name", "date"}
REQUIRED_VALUE_NAME_HINT_TOKENS = ("명", "이름", "번호", "일자")

DETAIL_ADDRESS_PLACEHOLDER_VALUES = {
    "-",
    "--",
    "---",
    ".",
    "·",
    "없음",
    "해당없음",
    "해당없슴",
    "무",
    "미상",
    "불명",
    "N/A",
    "NA",
    "NULL",
    "NONE",
    "NAN",
}
COMPLETE_DETAIL_ADDRESS_VALUES = {
    "앞",
    "뒤",
    "정문",
    "후문",
    "입구",
    "출입구",
    "본관",
    "별관",
    "신관",
    "구관",
    "분관",
    "동관",
    "서관",
    "남관",
    "북관",
    "지상",
    "지하",
    "옥상",
    "주차장",
}
COMPLETE_DETAIL_ADDRESS_PATTERNS = (
    r"^[가-힣A-Z]\d?동$",
    r"^(?:B|지하)\d+층?$",
    r"^\d+층$",
    r"^\d+호$",
)

DATE_COLUMN_NAME_TOKENS = (
    "일자",
    "일시",
    "날짜",
    "년월",
    "연도",
    "년도",
    "등록일",
    "기준일",
    "개방일",
    "운영일",
    "시행일",
    "공개일",
    "마감일",
    "시작일",
    "종료일",
    "접수일",
    "처리일",
    "발생일",
    "생성일",
    "수정일",
    "갱신일",
)
TIME_ONLY_COLUMN_NAME_TOKENS = ("시간", "시각")

BOOLEAN_ALLOWED_VALUES = {"y", "n", "yes", "no", "true", "false", "0", "1", "예", "아니오", "유", "무"}
DATE_PATTERNS = (
    "%Y-%m-%d",
    "%Y%m%d",
    "%Y.%m.%d",
    "%Y/%m/%d",
    "%Y-%m",
    "%Y%m",
    "%Y",
    "%Y년",
    "%Y-%m-%d %H:%M:%S",
    "%Y%m%d%H%M%S",
)
MANUAL_REVIEW_RULE_IDS = {
    "manual_review_required",
    "categorical_value_manual_review",
    "categorical_value_normalization",
    "date_format_inconsistent",
    "row_context_manual_review",
}
RULE_SEVERITY_BY_RULE_ID = {
    "manual_review_required": "info",
    "categorical_value_manual_review": "info",
    "categorical_value_normalization": "info",
    "date_format_inconsistent": "info",
    "row_context_manual_review": "info",
    "garbled_text": "error",
    "whitespace_issue": "warning",
    "special_character_issue": "warning",
    "required_value": "warning",
    "duplicate_data": "warning",
    "date_domain": "warning",
    "number_domain": "warning",
    "boolean_domain": "warning",
    "amount_domain": "warning",
    "quantity_domain": "warning",
    "rate_domain": "warning",
    "categorical_semantic_domain": "warning",
    "categorical_value_out_of_domain": "warning",
    "categorical_value_truncated": "warning",
    "logical_consistency": "warning",
    "calculation_formula": "warning",
    "reference_relation": "warning",
    "address_region_prefix_mismatch": "warning",
    "time_sequence_consistency": "error",
    "precedence_accuracy": "warning",
}
SEVERITY_VALUES = {"info", "warning", "error"}

FREE_TEXT_COLUMN_NAME_TOKENS = {
    "기타",
    "기타사항",
    "기타내용",
    "기타설명",
    "비고",
    "비고사항",
    "메모",
    "참고",
    "참고사항",
    "내용",
    "설명",
    "상세내용",
    "사유",
    "특이사항",
    "안내",
    "조치",
    "민원",
    "서비스URL",
    "서비스url",
    "서비스링크",
    "사이트",
    "홈페이지",
    "URL",
    "url",
    "링크",
    "대표문의",
    "문의처",
}

VALIDATION_CRITERIA = {
    "relation_consistency": {
        "label": "데이터 관계 정합성",
        "criteria": {
            "time_sequence_consistency": "시간순서 관계를 갖는 컬럼 간의 데이터 오류 측정",
            "precedence_accuracy": "선후관계를 가지는 컬럼 간의 데이터 오류 측정",
            "logical_consistency": "컬럼 간 관계에 따른 특정 컬럼의 논리적 일관성 오류를 측정",
            "calculation_formula": "원천데이터의 계산 등을 통해 저장되는 계산 값이 정확하게 관리되고 있는지를 측정",
            "reference_relation": "참조하는 컬럼과 참조되는 컬럼 사이의 일관성이 유지되는지 측정",
        },
    },
    "completeness": {
        "label": "컬럼 완결성 검증",
        "criteria": {
            "garbled_text": "컬럼명, 데이터 값에 깨진 글자 또는 완성된 한글이 아닌 데이터 오류 측정",
            "whitespace_special_characters": "컬럼명, 데이터 값에 불필요한 공백과 특수문자가 입력된 오류 측정",
            "required_value": "데이터의 특성 상 반드시 입력되어야 하는 값은 누락없이 제공되어야 함",
            "duplicate_data": "DB 내 두 개 이상 테이블(또는 파일)에 존재하는 동일한(중복) 데이터의 값 일치 여부 측정",
        },
    },
    "domain_validity": {
        "label": "컬럼 특성 유효성 검증",
        "criteria": {
            "date_domain": "날짜 데이터를 저장하는 컬럼의 데이터 값이 유효한 범위를 벗어나는 오류를 측정",
            "number_domain": "정해진 규칙 등에 따라 관리되는 번호 도메인 데이터 오류를 측정",
            "boolean_domain": "여부/유무 등 2값 분류 도메인 컬럼의 유효값 범위 이탈 오류를 측정",
            "code_domain": "코드 또는 분류값이 컬럼 의미와 일관되게 적용되는지를 측정",
            "categorical_semantic_domain": "범주형 문자열 컬럼의 고유값이 동일 도메인 체계와 의미적으로 일관되게 사용되는지를 측정",
            "amount_domain": "숫자로 저장된 금액 도메인 컬럼의 값이 유효한 범위를 벗어나는 오류를 측정",
            "quantity_domain": "숫자로 저장된 수량 도메인 컬럼의 값이 유효한 범위를 벗어나는 오류를 측정",
            "rate_domain": "숫자로 저장된 율 도메인 컬럼의 값이 유효한 범위를 벗어나는 오류를 측정",
        },
    },
}

LLM_SEMANTIC_PROFILE_ALWAYS_TRIGGER_TAGS = {"address"}
LLM_SEMANTIC_PROFILE_SKIP_TAGS = {
    "date",
    "phone",
    "geo_lat",
    "geo_lon",
    "coordinate_pair",
    "boolean",
    "amount",
    "quantity",
    "count",
    "rate",
    "width",
}
LLM_SEMANTIC_PROFILE_AMBIGUOUS_TERMS = {
    "구분",
    "상태",
    "코드",
    "번호",
    "명",
    "명칭",
    "값",
    "내용",
    "유형",
    "종류",
    "정보",
    "데이터",
}

CATEGORICAL_LLM_MIN_REPEAT_COUNT = 2

__all__ = [
    "BOOLEAN_ALLOWED_VALUES",
    "CATEGORICAL_LLM_MIN_REPEAT_COUNT",
    "COMPLETE_DETAIL_ADDRESS_PATTERNS",
    "COMPLETE_DETAIL_ADDRESS_VALUES",
    "DATE_COLUMN_NAME_TOKENS",
    "DATE_PATTERNS",
    "DETAIL_ADDRESS_PLACEHOLDER_VALUES",
    "FREE_TEXT_COLUMN_NAME_TOKENS",
    "FREE_TEXT_LONG_SAMPLE_MIN_COUNT",
    "FREE_TEXT_LONG_SAMPLE_MIN_LENGTH",
    "FREE_TEXT_STRUCTURED_NAME_TOKENS",
    "FREE_TEXT_STRUCTURED_TAGS",
    "LLM_SEMANTIC_PROFILE_ALWAYS_TRIGGER_TAGS",
    "LLM_SEMANTIC_PROFILE_AMBIGUOUS_TERMS",
    "LLM_SEMANTIC_PROFILE_SKIP_TAGS",
    "MANUAL_REVIEW_RULE_IDS",
    "NUMERIC_PAIR_BASE_STEM_TOKENS",
    "REFERENCE_PAIR_TOKENS",
    "REQUIRED_VALUE_NAME_HINT_TOKENS",
    "REQUIRED_VALUE_NON_UNIQUE_NAME_TOKENS",
    "REQUIRED_VALUE_NULL_MAX_RATIO",
    "REQUIRED_VALUE_OPTIONAL_NAME_TOKENS",
    "REQUIRED_VALUE_TAGS",
    "REQUIRED_VALUE_UNIQUE_IDENTIFIER_NAME_TOKENS",
    "RULE_SEVERITY_BY_RULE_ID",
    "SEVERITY_VALUES",
    "TIME_ONLY_COLUMN_NAME_TOKENS",
    "TIME_ORDER_TOKENS",
    "VALIDATION_CRITERIA",
]
